"""empty message

Revision ID: 0e6917872a11
Revises: 9c2e3a58e4a1
Create Date: 2023-12-05 23:03:11.720170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6917872a11'
down_revision = '9c2e3a58e4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.alter_column('company_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.alter_column('company_description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
